// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwtdbcbrqlmytwisgqil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3dGRiY2JycWxteXR3aXNncWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzg5NjUsImV4cCI6MjA2NjYxNDk2NX0.a3CbVKSIEDk64uuqSOmDCj4TntSCp4gL6sBFg6y1XDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);